title: Soundwave
description: Produção de eventos
url: "https://www.soundwaveproducoes.pt"

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post